name: "Flake Check"
on:
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = surrealdb.cachix.org-1:rbm7Qs+s36pxbfk9jhIa5HRld6gZ63koZz1h/9sSxaA=
            substituters = https://surrealdb.cachix.org
      # - uses: DeterminateSystems/magic-nix-cache-action@v9
      #   with:
      #     extra_nix_config: |
      #       access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
